document.getElementById("hname").innerText="BRIAN DUDEY";
document.getElementById("stline").innerText="N.Damen Avenue, Chicago 999999 | 999-999-9999- | hello@gmail.com | www.kickresume.com"
document.getElementById("profile").innerText="Profile";
document.getElementById("profilecon").innerText="Innovative optimized solution seeker. Excited to be atthe deployment phase of my new career as a webdeveloper. I am ambitious, adventurous, assiduous, animated, and an alliteration advocate.";
document.getElementById("skills").innerText="Skills";
document.getElementById("skill").innerHTML="JavaScript <br> CSS <br> HTML <br> REACT <br> REDUX <br> MONGO <br> Deployment"
document.getElementById("askil").innerHTML="Project Management <br> Recruitment <br> Business Development <br> Editing <br> Fundraising";
document.getElementById("work").innerHTML="<b>Event Manager</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;03/2014 - 02/2017 C3 Presents, Washington DC <ul> <li>Lead and execute all phases of event planning and production spanning committee recruitment, training, vendor relationships and on-site facilitation.</li> <li>Brought new business to the organization through relentless networking and stewardship which helped the company win the bid for the State Department Summit on the Middle East and, the companies largest civic event to date, the United State of Women</li> <li>Exercise fiscal control over budget creation, tracking and reporting. Collaborate with employees at all organizational levels to advance cohensive operations.</li> </ul> </div>";
document.getElementById("work1").innerHTML="<b>Community Relations </b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 06/2011 - 01/2014 <b>Manager</b><br> Gay & lesbian Elder Housing, Los Angeles <ul> <li>Arranging presentations and pitch deck.</li> <li>Designing a PR plan and establishing important focus points.</li> <li>Designing, creating and managing content across multiple communication platforms.</li> <li>Building relationships with key media players.</li> </ul>"
document.getElementById("educa").innerHTML="<br><br> <b>Engineering Immersion</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11/2018 - 06/2018 <b>Program</b><br> Thinkful, Chicago, IL <br><br> Project-focused intensive program with emphasis on Mongo, Express, React, and JavaScript (MERN) technical stack. <br> <ul> <li>Developed a full-stack web application, RenewU, using React that allows users to explore various aspects of meditation. User's progress is stored on a backend created using Node and MongoDB.</li> <li>Developed a language learning app, Foodie Phonetics using spaced repetition and a linked list data structure. React was used to create the front end components while Node and Mongo were used to create a backend that stores user data.</li> <li>Developed a concierge app, Pley, for individuals looking for curated suggestions when visiting a new place. React was used to develop the front end which includes real-time chat, drag and drop and variety of advanced features. The backend, built using Node, Express, and Mongo, takes advantage of well-developed RESTful API, Geospatial searching, and user authentication with JWT.</li> </ul> <b>BA, English</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 09/2001 - 09/2005 <br> University of California, Los Angles"

